services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: rtm-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: rtm-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"      # inside Docker network
      - "29092:29092"    # reachable from your host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: rtm-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  postgres:
    image: postgres:16
    container_name: rtm-postgres
    environment:
      POSTGRES_USER: rtm
      POSTGRES_PASSWORD: rtm
      POSTGRES_DB: rtm
    ports:
      - "5432:5432"
    volumes:
      - rtm-postgres-data:/var/lib/postgresql/data

  producer:
    build: ./producer
    container_name: rtm-producer
    depends_on:
      - kafka
    environment:
      PYTHONUNBUFFERED: 1

  consumer:
    build: ./consumer
    container_name: rtm-consumer
    depends_on:
      - kafka
      - postgres
    environment:
      PYTHONUNBUFFERED: 1

  grafana:
    image: grafana/grafana:10.4.1
    container_name: rtm-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning


  anomaly-detector:
    build: ./anomaly-detector
    container_name: rtm-anomaly-detector
    depends_on:
      - kafka
    environment:
      PYTHONUNBUFFERED: 1



volumes:
  rtm-postgres-data:
  grafana-data: